# Generated by Django 5.0.7 on 2024-07-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="booking_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
